name: Merge main into container
on:
  push:
    branches:
      - main
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Checkout container branch
        run: git checkout container
      - name: Merge main branch into container
        run: |
          git merge main --no-edit
          git push
      - name: Cleanup
        run: |
          git checkout main
